"""Seed Batch 1 — domain rules for 6 of 10 canonical document types.

Wired into GLOBAL_RULES via rules_registry. Analyzer execution for graph-backed
checks may still be pending; metadata (ownership, risk_id, ontology) is stored
in logic_config for the Risk Engine / future runners.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from app.models import DocumentCategory, RiskSeverity

if TYPE_CHECKING:
    from app.knowledge.rules_registry import RuleDef


def build_seed_batch1_rules() -> list[RuleDef]:
    # Lazy import avoids circular load with rules_registry
    from app.knowledge.rules_registry import RuleDef
    from app.knowledge.seed_i18n import localized_seed_fields

    def _seed(
        *,
        code: str,
        document_type: str,
        category: str,
        ownership_tag: str,
        ontology_entities: list[str],
        risk_id: str,
        description_en: str,
        title_en: str,
        severity: RiskSeverity,
        impact_fin: str,
        impact_sch: str,
        requires: DocumentCategory | None = None,
        applies: list[DocumentCategory] | None = None,
        check: str = "seed_pending",
        extra: dict[str, Any] | None = None,
    ) -> RuleDef:
        cfg: dict[str, Any] = {
            "seed_batch": 1,
            "document_type": document_type,
            "validation_category": category,
            "ownership_tag": ownership_tag,
            "ontology_entities": ontology_entities,
            "risk_id": risk_id,
            "check": check,
        }
        if extra:
            cfg.update(extra)
        title, description, recommendation = localized_seed_fields(code, title_en, description_en)
        return RuleDef(
            code=code,
            category=category.replace("-", "_"),
            severity=severity,
            title=title,
            description=description,
            recommendation=recommendation,
            financial_impact=impact_fin,
            schedule_impact=impact_sch,
            requires_category=requires,
            applies_to=applies or ([] if requires is None else [requires]),
            logic_config=cfg,
            keywords_any=[],
        )

    DT_SCHED = "Construction Schedule"
    DT_CON = "Contract Documents"
    DT_SPEC = "Technical Specifications"
    DT_BOQ = "Bill of Quantities (BOQ)"
    DT_DRAW = "Engineering Drawings"
    DT_TEND = "Tender Documents"

    INTRA = "intra-document"
    INTER = "inter-document"
    STD = "standard-compliance"

    return [
        # ----- Construction Schedule -----
        _seed(
            code="SCH-SEED-001",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="PYTHON",
            ontology_entities=["Activity", "Schedule", "Dependency"],
            risk_id="RISK-SCHED-ISLAND-001",
            title_en="Island / floating activity (no predecessor or successor)",
            description_en="Non-terminal activity lacks both predecessor and successor links.",
            severity=RiskSeverity.MEDIUM,
            impact_fin="medium",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_orphan_activity",
        ),
        _seed(
            code="SCH-SEED-002",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="PYTHON",
            ontology_entities=["Activity", "Milestone"],
            risk_id="RISK-SCHED-DURATION-001",
            title_en="Zero or negative duration on non-milestone activity",
            description_en="Activity marked as work has duration ≤ 0.",
            severity=RiskSeverity.HIGH,
            impact_fin="low",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_invalid_duration",
        ),
        _seed(
            code="SCH-SEED-003",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="PYTHON",
            ontology_entities=["Activity"],
            risk_id="RISK-SCHED-DURATION-001",
            title_en="End date earlier than start date",
            description_en="Activity finish < start.",
            severity=RiskSeverity.HIGH,
            impact_fin="low",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_end_before_start",
        ),
        _seed(
            code="SCH-SEED-004",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="HYBRID",
            ontology_entities=["Activity", "Schedule", "Project"],
            risk_id="RISK-SCHED-CRITICALPATH-001",
            title_en="Unreasonable critical-path length vs project logic",
            description_en="Python flags outlier CP length; AI explains feasibility/claim risk.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_cp_outlier",
        ),
        _seed(
            code="SCH-SEED-005",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="PYTHON",
            ontology_entities=["Activity", "Dependency"],
            risk_id="RISK-SCHED-FLOAT-001",
            title_en="Negative float on activities",
            description_en="Negative float indicates relationship contradiction in the network.",
            severity=RiskSeverity.HIGH,
            impact_fin="medium",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_negative_float",
        ),
        _seed(
            code="SCH-SEED-006",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="HYBRID",
            ontology_entities=["Activity", "Dependency"],
            risk_id="RISK-SCHED-LAG-001",
            title_en="Missing or incorrect Lag/Lead in relationships",
            description_en="Python detects missing/abnormal lag-lead; AI explains sequencing risk.",
            severity=RiskSeverity.MEDIUM,
            impact_fin="medium",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_lag_lead",
        ),
        _seed(
            code="SCH-SEED-007",
            document_type=DT_SCHED,
            category=INTER,
            ownership_tag="PYTHON",
            ontology_entities=["Schedule", "Contract", "Contract Clause", "Milestone"],
            risk_id="RISK-SCHED-NTP-MISMATCH-001",
            title_en="Programme start vs Contract notice-to-proceed date mismatch",
            description_en="Cross-document: schedule project start ≠ contract NTP / commencement date.",
            severity=RiskSeverity.HIGH,
            impact_fin="medium",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            applies=[DocumentCategory.SCHEDULE, DocumentCategory.TENDER],
            check="schedule_vs_contract_ntp",
            extra={"cross_document_types": ["Construction Schedule", "Contract Documents"]},
        ),
        _seed(
            code="SCH-SEED-008",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="HYBRID",
            ontology_entities=["Activity"],
            risk_id="RISK-SCHED-OVERLAP-001",
            title_en="Duplicate or overlapping activities without justification",
            description_en="Python detects duplicate/overlap; AI assesses whether logic justifies it.",
            severity=RiskSeverity.MEDIUM,
            impact_fin="medium",
            impact_sch="medium",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_overlap_duplicate",
        ),
        _seed(
            code="SCH-SEED-009",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="PYTHON",
            ontology_entities=["Activity", "Labor", "Equipment"],
            risk_id="RISK-SCHED-RESOURCE-001",
            title_en="No resources assigned to main activities",
            description_en="Critical/high-duration activities lack resource assignments when schema provides them.",
            severity=RiskSeverity.MEDIUM,
            impact_fin="medium",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_missing_resources",
        ),
        _seed(
            code="SCH-SEED-010",
            document_type=DT_SCHED,
            category=INTRA,
            ownership_tag="PYTHON",
            ontology_entities=["Activity", "Milestone", "Schedule"],
            risk_id="RISK-SCHED-HANDOVER-001",
            title_en="Missing handover milestones at schedule end",
            description_en="Missing administrative / provisional / final handover activities near programme end.",
            severity=RiskSeverity.MEDIUM,
            impact_fin="medium",
            impact_sch="high",
            requires=DocumentCategory.SCHEDULE,
            check="schedule_missing_handover",
        ),
        # ----- Contract Documents -----
        _seed(
            code="CON-SEED-001",
            document_type=DT_CON,
            category=INTRA,
            ownership_tag="AI",
            ontology_entities=["Contract Clause", "Employer", "Contractor", "Contract"],
            risk_id="RISK-CON-RESP-AMBIG-001",
            title_en="Ambiguous Employer vs Contractor responsibility in a clause",
            description_en="Semantic ambiguity in responsibility allocation for a specific clause.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="high",
            requires=DocumentCategory.TENDER,
            check="contract_responsibility_ambiguity",
            extra={"cdm_subtype_hint": ["contract", "general_conditions", "particular_conditions"]},
        ),
        _seed(
            code="CON-SEED-002",
            document_type=DT_CON,
            category=INTER,
            ownership_tag="HYBRID",
            ontology_entities=["Contract Clause", "Tender", "Requirement", "Document"],
            risk_id="RISK-CON-VS-ITT-001",
            title_en="Contract clauses contradict Tender Documents (duration/deadlines)",
            description_en="Python cross-detects differing duration/deadlines; AI interprets binding conflict risk.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="high",
            requires=DocumentCategory.TENDER,
            check="contract_vs_itt_deadlines",
            extra={"cross_document_types": ["Contract Documents", "Tender Documents"]},
        ),
        _seed(
            code="CON-SEED-003",
            document_type=DT_CON,
            category=INTRA,
            ownership_tag="AI",
            ontology_entities=["Contract Clause", "Payment", "Constraint"],
            risk_id="RISK-CON-BOND-AMBIG-001",
            title_en="Ambiguous or legally contradictory guarantee/bond clauses",
            description_en="Guarantee/bond wording is ambiguous or internally contradictory.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="medium",
            requires=DocumentCategory.TENDER,
            check="contract_bond_ambiguity",
        ),
        _seed(
            code="CON-SEED-004",
            document_type=DT_CON,
            category=INTER,
            ownership_tag="HYBRID",
            ontology_entities=["Contract Clause", "BOQ Item", "Requirement"],
            risk_id="RISK-CON-VS-BOQ-SCOPE-001",
            title_en="Stated scope/work volume contradicts BOQ quantities",
            description_en="Python detects numeric/scope mismatch vs BOQ; AI explains claim exposure.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="medium",
            requires=DocumentCategory.TENDER,
            check="contract_vs_boq_scope",
            extra={"cross_document_types": ["Contract Documents", "Bill of Quantities (BOQ)"]},
        ),
        # ----- Technical Specifications -----
        _seed(
            code="SPEC-SEED-001",
            document_type=DT_SPEC,
            category=STD,
            ownership_tag="HYBRID",
            ontology_entities=["Document Section", "Requirement", "Standard", "StandardVersion", "Project"],
            risk_id="RISK-SPEC-STD-MISMATCH-001",
            title_en="Referenced standards/codes do not match project type",
            description_en="Cited codes inconsistent with project typology; Python lists citations, AI judges fitness.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="medium",
            requires=DocumentCategory.TENDER,
            check="specs_standards_vs_project_type",
            extra={"cdm_subtype_hint": ["specs", "particular_specs"]},
        ),
        _seed(
            code="SPEC-SEED-002",
            document_type=DT_SPEC,
            category=INTRA,
            ownership_tag="AI",
            ontology_entities=["Requirement", "Material", "Document Section"],
            risk_id="RISK-SPEC-MISSING-GRADE-001",
            title_en="Missing technical specification for sensitive items (e.g. concrete/steel grade)",
            description_en="Sensitive materials/systems lack grade/performance specification.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="medium",
            requires=DocumentCategory.TENDER,
            check="specs_missing_sensitive_grades",
        ),
        _seed(
            code="SPEC-SEED-003",
            document_type=DT_SPEC,
            category=INTER,
            ownership_tag="HYBRID",
            ontology_entities=["Requirement", "Drawing Sheet", "Wall", "Material"],
            risk_id="RISK-SPEC-VS-DRAW-001",
            title_en="Specification requirements inconsistent with Engineering Drawings",
            description_en="Cross-document inconsistency between specs and drawings.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="high",
            requires=DocumentCategory.TENDER,
            applies=[DocumentCategory.TENDER, DocumentCategory.DRAWING],
            check="specs_vs_drawings",
            extra={"cross_document_types": ["Technical Specifications", "Engineering Drawings"]},
        ),
        # ----- BOQ -----
        _seed(
            code="BOQ-SEED-001",
            document_type=DT_BOQ,
            category=INTER,
            ownership_tag="PYTHON",
            ontology_entities=["BOQ Item", "Drawing Sheet", "Document Section", "Requirement"],
            risk_id="RISK-BOQ-UNIT-MISMATCH-001",
            title_en="Unit of measurement mismatch with Drawings or Specifications",
            description_en="BOQ unit conflicts with unit implied/stated on drawings or specs.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="medium",
            requires=DocumentCategory.TENDER,
            applies=[DocumentCategory.TENDER, DocumentCategory.DRAWING],
            check="boq_unit_mismatch",
            extra={"cross_document_types": ["Bill of Quantities (BOQ)", "Engineering Drawings", "Technical Specifications"]},
        ),
        _seed(
            code="BOQ-SEED-002",
            document_type=DT_BOQ,
            category=INTER,
            ownership_tag="PYTHON",
            ontology_entities=["BOQ Item", "Drawing", "Drawing Sheet"],
            risk_id="RISK-BOQ-DRAW-ABSENCE-001",
            title_en="Item on Drawing absent in BOQ (or vice versa)",
            description_en="Presence asymmetry between quantified drawing objects and BOQ items.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="medium",
            requires=DocumentCategory.TENDER,
            applies=[DocumentCategory.TENDER, DocumentCategory.DRAWING],
            check="boq_vs_drawing_presence",
            extra={"cross_document_types": ["Bill of Quantities (BOQ)", "Engineering Drawings"]},
        ),
        _seed(
            code="BOQ-SEED-003",
            document_type=DT_BOQ,
            category=INTRA,
            ownership_tag="PYTHON",
            ontology_entities=["BOQ Item", "Table"],
            risk_id="RISK-BOQ-MATH-001",
            title_en="Mathematical summation / extension errors",
            description_en="qty×rate≠extension or category/grand totals do not reconcile.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="low",
            requires=DocumentCategory.TENDER,
            check="boq_math_totals",
        ),
        _seed(
            code="BOQ-SEED-004",
            document_type=DT_BOQ,
            category=STD,
            ownership_tag="PYTHON",
            ontology_entities=["BOQ Item", "Standard"],
            risk_id="RISK-BOQ-CODING-001",
            title_en="Item coding inconsistent with Fehrest Baha / GAEB reference",
            description_en="Position codes fail country BOQ coding scheme checks (Fehrest/GAEB).",
            severity=RiskSeverity.MEDIUM,
            impact_fin="medium",
            impact_sch="low",
            requires=DocumentCategory.TENDER,
            check="boq_coding_scheme",
            extra={"boq_formats": ["fehrest_baha", "gaeb"]},
        ),
        _seed(
            code="BOQ-SEED-005",
            document_type=DT_BOQ,
            category=INTRA,
            ownership_tag="HYBRID",
            ontology_entities=["BOQ Item", "Building", "Location", "Project"],
            risk_id="RISK-BOQ-QTY-OUTLIER-001",
            title_en="Unreasonable quantities relative to project area/volume",
            description_en="Python flags quantity outliers vs area/volume; AI assesses realism.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="medium",
            requires=DocumentCategory.TENDER,
            check="boq_qty_vs_area",
        ),
        # ----- Engineering Drawings -----
        _seed(
            code="DRAW-SEED-001",
            document_type=DT_DRAW,
            category=INTER,
            ownership_tag="PYTHON",
            ontology_entities=["Drawing Sheet", "Revision", "Drawing"],
            risk_id="RISK-DRAW-REV-MISMATCH-001",
            title_en="Revision mismatch across architectural/structural/MEP drawings",
            description_en="Cross-discipline revision identifiers are inconsistent for the same issue set.",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="high",
            requires=DocumentCategory.DRAWING,
            check="drawing_revision_mismatch",
        ),
        _seed(
            code="DRAW-SEED-002",
            document_type=DT_DRAW,
            category=INTRA,
            ownership_tag="HYBRID",
            ontology_entities=["Drawing Sheet", "Figure"],
            risk_id="RISK-DRAW-SCALE-001",
            title_en="Scale inconsistent with stated dimensions",
            description_en="Python/vision compares stated scale vs measured dimension ratios; AI explains if needed.",
            severity=RiskSeverity.MEDIUM,
            impact_fin="medium",
            impact_sch="medium",
            requires=DocumentCategory.DRAWING,
            check="drawing_scale_vs_dimensions",
            extra={"may_use_vision": True},
        ),
        _seed(
            code="DRAW-SEED-003",
            document_type=DT_DRAW,
            category=INTRA,
            ownership_tag="AI",
            ontology_entities=["Drawing Detail", "Drawing Sheet", "Connection"],
            risk_id="RISK-DRAW-MISSING-DETAIL-001",
            title_en="Missing execution detail for critical connections",
            description_en="Critical connection/junction lacks executable detail (AI/vision-assisted).",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="high",
            requires=DocumentCategory.DRAWING,
            check="drawing_missing_connection_detail",
            extra={"may_use_vision": True},
        ),
        _seed(
            code="DRAW-SEED-004",
            document_type=DT_DRAW,
            category=INTRA,
            ownership_tag="AI",
            ontology_entities=["Drawing Sheet", "Level", "Wall"],
            risk_id="RISK-DRAW-PLAN-SECTION-001",
            title_en="Contradiction between plan view and section/elevation",
            description_en="Plan vs section/elevation inconsistency (AI/vision-assisted).",
            severity=RiskSeverity.HIGH,
            impact_fin="high",
            impact_sch="high",
            requires=DocumentCategory.DRAWING,
            check="drawing_plan_vs_section",
            extra={"may_use_vision": True},
        ),
        # ----- Tender Documents -----
        _seed(
            code="TEN-SEED-001",
            document_type=DT_TEND,
            category=INTER,
            ownership_tag="PYTHON",
            ontology_entities=["Tender", "Schedule", "Milestone", "Document"],
            risk_id="RISK-TEN-DEADLINE-MISMATCH-001",
            title_en="Deadline mismatch: invitation vs tender docs vs Construction Schedule",
            description_en="Closing/start/completion deadlines disagree across ITT, tender pack, and programme.",
            severity=RiskSeverity.HIGH,
            impact_fin="medium",
            impact_sch="high",
            requires=DocumentCategory.TENDER,
            applies=[DocumentCategory.TENDER, DocumentCategory.SCHEDULE],
            check="itt_vs_schedule_deadlines",
            extra={"cross_document_types": ["Tender Documents", "Construction Schedule", "Contract Documents"]},
        ),
        _seed(
            code="TEN-SEED-002",
            document_type=DT_TEND,
            category=INTRA,
            ownership_tag="AI",
            ontology_entities=["Tender", "Requirement", "Table"],
            risk_id="RISK-TEN-EVAL-UNCLEAR-001",
            title_en="Unclear technical-financial evaluation criteria",
            description_en="Evaluation criteria for technical/financial scoring are vague or non-measurable.",
            severity=RiskSeverity.HIGH,
            impact_fin="medium",
            impact_sch="high",
            requires=DocumentCategory.TENDER,
            check="itt_evaluation_unclear",
            extra={"cdm_subtype_hint": ["itt", "instructions_to_tenderers"]},
        ),
        _seed(
            code="TEN-SEED-003",
            document_type=DT_TEND,
            category=INTER,
            ownership_tag="PYTHON",
            ontology_entities=["Tender", "Document", "Document Section", "Change"],
            risk_id="RISK-TEN-XREF-INCOMPLETE-001",
            title_en="Incomplete numbering/cross-references between appendices and Addenda",
            description_en=(
                "Appendix or annex numbering/cross-references in Tender Documents are incomplete "
                "or do not resolve to uploaded appendices/Addenda."
            ),
            severity=RiskSeverity.MEDIUM,
            impact_fin="medium",
            impact_sch="medium",
            requires=DocumentCategory.TENDER,
            check="itt_appendix_addenda_xrefs",
            extra={
                "cdm_subtype_hint": ["itt", "instructions_to_tenderers", "tender_data"],
                "cross_document_types": ["Tender Documents", "Addenda"],
            },
        ),
    ]


# ---------------------------------------------------------------------------
# New Risk IDs to add to Part 5 RKB (seed catalog)
# ---------------------------------------------------------------------------

NEW_RISK_IDS_BATCH1: list[dict[str, str]] = [
    {
        "risk_id": "RISK-SCHED-ISLAND-001",
        "category": "delay",
        "description": "Floating/island activities break network integrity and hide true critical path.",
        "cost_impact": "medium",
        "schedule_impact": "high",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-SCHED-DURATION-001",
        "category": "delay",
        "description": "Invalid activity durations (zero/negative or end-before-start) invalidate the programme.",
        "cost_impact": "low",
        "schedule_impact": "high",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-SCHED-CRITICALPATH-001",
        "category": "delay",
        "description": "Critical path length unrealistic relative to scope/logic — tender programme not credible.",
        "cost_impact": "high",
        "schedule_impact": "high",
        "quality_impact": "medium",
    },
    {
        "risk_id": "RISK-SCHED-FLOAT-001",
        "category": "claim",
        "description": "Negative float signals logic contradictions and foreshadows EOT/disruption disputes.",
        "cost_impact": "medium",
        "schedule_impact": "high",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-SCHED-LAG-001",
        "category": "delay",
        "description": "Incorrect or missing lag/lead distorts sequencing and resource peaks.",
        "cost_impact": "medium",
        "schedule_impact": "high",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-SCHED-NTP-MISMATCH-001",
        "category": "claim",
        "description": "Programme start inconsistent with contractual notice-to-proceed / commencement.",
        "cost_impact": "medium",
        "schedule_impact": "high",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-SCHED-OVERLAP-001",
        "category": "constructability",
        "description": "Unjustified overlapping/duplicate activities create false progress and site conflict.",
        "cost_impact": "medium",
        "schedule_impact": "medium",
        "quality_impact": "medium",
    },
    {
        "risk_id": "RISK-SCHED-RESOURCE-001",
        "category": "delay",
        "description": "Main activities without resources imply unbuildable or underpriced programme.",
        "cost_impact": "medium",
        "schedule_impact": "high",
        "quality_impact": "medium",
    },
    {
        "risk_id": "RISK-SCHED-HANDOVER-001",
        "category": "delay",
        "description": "Missing provisional/final handover activities omit contractual completion path.",
        "cost_impact": "medium",
        "schedule_impact": "high",
        "quality_impact": "medium",
    },
    {
        "risk_id": "RISK-CON-RESP-AMBIG-001",
        "category": "claim",
        "description": "Ambiguous Employer/Contractor responsibility allocation in contract clauses.",
        "cost_impact": "high",
        "schedule_impact": "high",
        "quality_impact": "medium",
    },
    {
        "risk_id": "RISK-CON-VS-ITT-001",
        "category": "claim",
        "description": "Contract contradicts tender invitation on time/deadlines — unequal bidding basis.",
        "cost_impact": "high",
        "schedule_impact": "high",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-CON-BOND-AMBIG-001",
        "category": "commercial",
        "description": "Ambiguous or contradictory bond/guarantee clauses create enforcement and bid risk.",
        "cost_impact": "high",
        "schedule_impact": "medium",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-CON-VS-BOQ-SCOPE-001",
        "category": "cost",
        "description": "Contractual scope/volume statements conflict with BOQ quantities.",
        "cost_impact": "high",
        "schedule_impact": "medium",
        "quality_impact": "medium",
    },
    {
        "risk_id": "RISK-SPEC-STD-MISMATCH-001",
        "category": "compliance",
        "description": "Specifications cite standards inappropriate for the project type/jurisdiction profile.",
        "cost_impact": "high",
        "schedule_impact": "medium",
        "quality_impact": "high",
    },
    {
        "risk_id": "RISK-SPEC-MISSING-GRADE-001",
        "category": "quality",
        "description": "Sensitive items lack grade/performance specification (e.g. concrete/steel).",
        "cost_impact": "high",
        "schedule_impact": "medium",
        "quality_impact": "high",
    },
    {
        "risk_id": "RISK-SPEC-VS-DRAW-001",
        "category": "claim",
        "description": "Technical specifications conflict with engineering drawings.",
        "cost_impact": "high",
        "schedule_impact": "high",
        "quality_impact": "high",
    },
    {
        "risk_id": "RISK-BOQ-UNIT-MISMATCH-001",
        "category": "cost",
        "description": "BOQ units disagree with drawings or specifications — measurement disputes.",
        "cost_impact": "high",
        "schedule_impact": "medium",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-BOQ-DRAW-ABSENCE-001",
        "category": "cost",
        "description": "Quantified work on drawings missing from BOQ (or BOQ items without drawing basis).",
        "cost_impact": "high",
        "schedule_impact": "medium",
        "quality_impact": "medium",
    },
    {
        "risk_id": "RISK-BOQ-MATH-001",
        "category": "cost",
        "description": "Arithmetic errors in BOQ extensions/totals undermine tender comparability.",
        "cost_impact": "high",
        "schedule_impact": "low",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-BOQ-CODING-001",
        "category": "compliance",
        "description": "BOQ item coding inconsistent with Fehrest Baha or GAEB scheme.",
        "cost_impact": "medium",
        "schedule_impact": "low",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-BOQ-QTY-OUTLIER-001",
        "category": "cost",
        "description": "Quantities unreasonable vs project area/volume — pricing or scope error risk.",
        "cost_impact": "high",
        "schedule_impact": "medium",
        "quality_impact": "medium",
    },
    {
        "risk_id": "RISK-DRAW-REV-MISMATCH-001",
        "category": "claim",
        "description": "Architectural/structural/MEP revision sets are not aligned.",
        "cost_impact": "high",
        "schedule_impact": "high",
        "quality_impact": "high",
    },
    {
        "risk_id": "RISK-DRAW-SCALE-001",
        "category": "quality",
        "description": "Drawing scale inconsistent with annotated dimensions.",
        "cost_impact": "medium",
        "schedule_impact": "medium",
        "quality_impact": "high",
    },
    {
        "risk_id": "RISK-DRAW-MISSING-DETAIL-001",
        "category": "constructability",
        "description": "Critical connections lack executable detail drawings.",
        "cost_impact": "high",
        "schedule_impact": "high",
        "quality_impact": "high",
    },
    {
        "risk_id": "RISK-DRAW-PLAN-SECTION-001",
        "category": "constructability",
        "description": "Plan view contradicts section/elevation — unbuildable or claim-prone design pack.",
        "cost_impact": "high",
        "schedule_impact": "high",
        "quality_impact": "high",
    },
    {
        "risk_id": "RISK-TEN-DEADLINE-MISMATCH-001",
        "category": "procurement",
        "description": "Deadlines disagree across invitation, tender documents, and construction schedule.",
        "cost_impact": "medium",
        "schedule_impact": "high",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-TEN-EVAL-UNCLEAR-001",
        "category": "procurement",
        "description": "Technical/financial evaluation criteria unclear — award challenge and retender risk.",
        "cost_impact": "medium",
        "schedule_impact": "high",
        "quality_impact": "low",
    },
    {
        "risk_id": "RISK-TEN-XREF-INCOMPLETE-001",
        "category": "procurement",
        "description": "Incomplete appendix/Addenda numbering or unresolved cross-references in tender pack.",
        "cost_impact": "medium",
        "schedule_impact": "medium",
        "quality_impact": "low",
    },
]
